### ISSUE TITLE
Footer support

### ISSUE THREAD

**Issue by evil159** [airbnb/MagazineLayout#18]
Layout currently supports headers, would be nice to add footer support as well. It, of course, can be emulated by appending an extra cell at the bottom of a section, but footers are much more convenient to work with.
Footer layout should be quite similar to headers', is there any obstacle that prevents them from being supported?

**Comment by bryankeller** [comment]
Hey @evil159 - adding footer support (as a supplementary view) seems reasonable. This isn't as high-priority for me as #12, especially since it can be implemented today using a cell (as you pointed out). I'll assign to myself, but feel free to re-assign to yourself if you want to tackle it, that way I know someone else is working on it!

**Comment by evil159** [comment]
Can't re-assign the issue but the PR #23 is opened.
