### ISSUE TITLE
Nib based cells dynamic sizing issues

### ISSUE THREAD

**Issue by diegorozen** [airbnb/MagazineLayout#22]
**Describe the bug**
When using a nib based cell, dynamic heights behave erratically

**To Reproduce**
1. See https://github.com/diegorozen/MagazineLayout/tree/nib_based_cells_bug, just the same sample app changed to use nibs
2. Initial cells height doesn't get constrained. The layout recovers after scrolling

**Additional context**
The issue can be somewhat mitigated by adding a setNeedsLayout() + LayoutIfNeeded() before MagazineLayoutCollectionViewCell.swift Line 59. I still see eventual glitches after rotating several times. Am I missing something in terms of configuration?

**Comment by fruitcoder** [comment]
After trying to integrate MagazineLayout in one of my projects I can confirm this issue. Since the layout of my cells is fairly complex, there is a strong resistance when scrolling down, then it hangs, then it relayouts. After that, the cell heights are computed correctly (in the current orientation).
Do you have any idea why nibs can cause the layout to misbehave? Afaik it's only the initialization process (`init(coder:)` and `awakeFromNib()` being called) that's different from a purely programmatic cell. If you need help fixing this or have any hint where to look for let me know!

**Comment by evil159** [comment]
It was the same for me. After some research and experimentation I discovered that manually adding constraint to cell's `contentView` + constraining cell's width makes the nib based cells behave correctly(theoretically the height calculation there should be faster, since Apple says `systemLayoutSizeFitting(_ targetSize:)` is expensive as it creates a new AutoLayout engine discards it afterwards, requiring it to solve all the constraints, without caching the previously computed results).
https://gist.github.com/evil159/79780f7d1eafa9b9aacea420112420c8

**Comment by fruitcoder** [comment]
Does it also show a small resize animation (from the default 150 to the actual height)?

**Comment by evil159** [comment]
No, cells are sized without animation.

**Comment by ergunemr** [comment]
I have faced the same issue, once i have create my cell ui in a different custom view with xib and place it into programmatically created cell using constraints, it works like a charm

**Comment by fruitcoder** [comment]
@evil159's solution fixed the problem for me with purely xib based cells as well

**Comment by brynbodayle** [comment]
Thank you for reporting this issue. Spent sometime looking into this issue and here's what I found:
- Using the sample project @diegorozen provided, I was able to reproduce the exact same issue even after changing the project to use a self-sizing `UICollectionViewFlowLayout`.
- I tried both sample projects using Xcode 11.0 beta 4 and iOS 13 and the issue was no longer reproducible (see screenshots below).
- Synthesizing this, it appears that **on pre-iOS 13 there are issues with using self-sizing collection view cells that are loaded from NIBs regardless of which collection view layout you use**. After doing some research, it looks like others have experienced this issue (see [this SO post](https://stackoverflow.com/questions/25895311/uicollectionview-self-sizing-cells-with-auto-layout)) and have used workarounds such as adding additional width/height constraints to the cell or changing the way the content view is constrained to the cell. Though, I think @ergunemr's recommendation to wrap a custom NIB view in a cell seems safer and more likely to avoid unsatisfiable constraints.

Here are the screenshots from my tests. There are some minor differences in the layout, but only take note of the cell height differences. In iOS 13, the cells are given their preferred height instead of remaining at the estimated height on the initial layout pass.

#### UICollectionViewFlowLayout
iOS 12 | iOS 13
------- | ------
![ios-12-flow-layout](https://user-images.githubusercontent.com/1455522/63305421-9494a600-c29b-11e9-9429-72e4853a841e.png) | ![after](https://user-images.githubusercontent.com/1455522/63305678-a62a7d80-c29c-11e9-80cc-12e6cd6f194c.png)

#### MagazineLayout
iOS 12 | iOS 13
------- | ------
![ios-12-flow-layout](https://user-images.githubusercontent.com/1455522/63305422-952d3c80-c29b-11e9-9736-36629dddf37e.png) | ![after](https://user-images.githubusercontent.com/1455522/63305679-a62a7d80-c29c-11e9-83dd-e4cb22369a0b.png)
