### ISSUE TITLE
Section insets

### ISSUE THREAD

**Issue by evil159** [airbnb/MagazineLayout#24]
**Is your feature request related to a problem? Please describe.**
`UICollectionViewFlowLayout` have frustrated me quite a few times with it's way to specify sections insets, which are not section insets but rather item insets. I guess item insets in `MagazineLayout` and their behaviour is modelled after `UICollectionViewFlowLayout`.
So my issue is - how do I specify section insets for a section? In a way that header and footer would also respect them. 

**Describe the solution you'd like**
I'd suggest adding a notion of `sectionInsets` to `MagazineLayout` sections could help this

**Describe alternatives you've considered**
Alternative way would be to add extra space at the top to section header(or the bottom of section footer) to *make it appear* as there is spacing between sections, but that appears more like a hack rather than a solution.

**Comment by bryankeller** [comment]
Thanks for the suggestion @evil159 - I'd like to keep this behavior consistent with flow layout, since it's what people expect.

If you need section 0 to be inset by a certain amount, just set contentInset.top to the value you'd like.

If you'd like subsequent sections to be inset by a certain amount, change the bottom section inset of the preceding section. Does that make sense?

**Comment by bryankeller** [comment]
Thanks for the suggestion @evil159 - you're correct that `itemInsets` is a more accurate name for the behavior flow layout has with `sectionInsets`.

This might be something we add support for. In the mean time, you can do this:

- If you need section 0 to be inset by a certain amount, just set contentInset.top to the value you'd like.
- If you'd like subsequent sections to be inset by a certain amount, change the bottom section inset of the preceding section. Does that make sense?

**Comment by jefflopes** [comment]
I just started using MagazineLayout and would love support for section insets. In the meantime I'm not sure I understand this specific suggested workaround:

> If you'd like subsequent sections to be inset by a certain amount, change the bottom section inset of the preceding section. Does that make sense?

How do I change the bottom section inset of the preceding section without the support requested in this issue? Is there some existing partial support I'm not seeing?

**Comment by bryankeller** [comment]
@jefflopes I'll prioritize adding support for this before other tasks, since I agree it's a shortcoming of the current configuration options. To elaborate on my workaround:

<img width="626" alt="Screen Shot 2019-04-08 at 11 29 45 AM" src="https://user-images.githubusercontent.com/746571/55747672-9e56f480-59f1-11e9-8d2d-b20fe9bba682.png">

So, you can effectively inset section 1, 2, 3... by providing a *bottom item inset > 0* for the previous section. So, as seen in the drawing, to inset section 1, provide a bottom item inset for section 0. To inset section 2, provide a bottom item inset for section 1. Etc.

You provide this inset by implementing the delegate function

```
func collectionView(
    _ collectionView: UICollectionView,
    layout collectionViewLayout: UICollectionViewLayout,
    insetsForItemsInSectionAtIndex index: Int)
    -> UIEdgeInsets
```

**Comment by jefflopes** [comment]
@bryankeller Got it now. Thanks for taking the time to draw this out. Super helpful.

**Comment by bryankeller** [comment]
@evil159 @jefflopes https://github.com/airbnb/MagazineLayout/pull/35

Bryn (who I requested for code review) is on vacation right now, so I'll aim to get this merged next week!
