### ISSUE TITLE
Collection view flickering on bounce

### ISSUE THREAD

**Issue by jefflopes** [airbnb/MagazineLayout#36]
**Describe the bug**
When you're at the top of the collection view and you continue scroll up, the collection view flickers during the bounce. It only happens on the first bounce after the collection view is loaded. If you scroll down and back up again everything looks fine.

**To Reproduce**
1. Download sample project: https://www.dropbox.com/s/iuj8pd0sz9p5pb0/MagazineLayoutIssue.zip?dl=0
2. Build & Run
3. Navigate to first tab
4. Scroll to top
5. Scroll past the top to invoke bounce 
6. Release to return to yOffset 0

**Expected behavior**
A smooth animation of the collection view back to yOffset 0

**Screenshots**
![Bounce Glitch](https://media.giphy.com/media/S992elOcUa5XF9CGa7/giphy.gif) 

**Smartphone (please complete the following information):**
 - Device/Simulator: iPhone 8 simulator, iPhone XS Max
 - OS: iOS 12.2
 - Version MagazineLayout 1.2.4

**Comment by jefflopes** [comment]
Might also be worth noting that it only happens when using dynamic height on cells. Fixed height cells don't reproduce the issue.

**Comment by bryankeller** [comment]
Hah, I knew exactly what this was as soon as I saw the GIF. You've stumbled upon rdar://40926834 (I'll move it over to open radar so others can read about it... 1 min), which causes jumpiness if self sizing cells are used + `collectionView.isPrefetchingEnabled = true`.

This issue is unrelated to MagazineLayout, and will happen for any self-sizing collection view, unfortunately.

To fix it, turn off prefetching until Apple fixes this (add `collectionView.isPrefetchingEnabled = false`).

**Comment by jefflopes** [comment]
@bryankeller Thank you! You just saved me days of frustration. I wonder if it's worth adding a note and link to the radar in your README given how common this might end up being for your users.

**Comment by bryankeller** [comment]
Agree @jefflopes - I'll add that

**Comment by bachand** [comment]
That’s a great idea. Maybe it will incentivize Apple to fix them ;)
