### ISSUE TITLE
Collection View Header

### ISSUE THREAD

**Issue by jamesblasco** [airbnb/MagazineLayout#38]
**Is your feature request related to a problem? Please describe.**
A lot of collection views nowadays requires a cell to be used as "header" of a collection view when we display detail information of a previous list of items. 
An example in airbnb would be a home. 

![HomePDP](https://user-images.githubusercontent.com/19904063/56469182-7ecebb80-6436-11e9-9983-5ec96a9c0bbf.png)
I have been working in a custom layout based on MagazineLayout for adding more powerful features to that top view. I think the most useful is to allow it to resize to a given compact size when scrolling and fix the view to the top when bouncing (making increase the height). 

**Describe the solution you'd like**
Add a new type of supplementary view as a main header and customize its behaviour while scrolling

Examples: 
This examples come from a real app I made myself
COMPACT SIZE -> Header bar size
![IMG_1872](https://user-images.githubusercontent.com/19904063/56469385-978ca080-6439-11e9-9cb3-0eef59ff970a.GIF)

COMPACT SIZE -> 0 (Background resize)
![IMG_1869](https://user-images.githubusercontent.com/19904063/56469387-978ca080-6439-11e9-9cfc-5f48db6be9da.GIF)

BOUNCING
![IMG_1873](https://user-images.githubusercontent.com/19904063/56469495-d707bc80-643a-11e9-9bed-934abf006c01.GIF)

 I would like to participate in the implementation if it's possible.

**Comment by bryankeller** [comment]
Hey @jamesblasco, nice looking app! I've done quite a lot of thinking around this (since long before the days of `MagazineLayout` actually!), and in general, I feel that these sorts of "headers" really don't belong to the layout or collection view. Here's some of my reasoning:

- What section does this view belong to? It seems quite odd for section 0's "special header" to still be on screen, even after section 0 is completely off-screen
- These headers almost always include navigation controls - Safari's, Facebook's, Airbnb's, and even `UINavigationBar` - all have expanding / collapsing behavior, while also containing navigation elements like back buttons, search bars, etc. To me, this further supports the idea that these are not collection view headers or cells.
- How would we support multiple expand / collapse behaviors? Safari's behaves differently from Airbnb's, which behaves differently than Facebook's, etc. This kind of customizability just really doesn't seem related to the layout of a collection of items, which is a collection view layout's main purpose 🙂 

----

So where does a top nav component like this belong? I would strongly advocate for it being a sibling view in your view hierarchy. Constrain it to the top of your view, update its height / collapse % based on the current scroll position, and call it a day 🙂 (You'll probably want to inset your collection view content by the maximum height of your header as well).

Perhaps this is a good time to shamelessly plug `BLKFlexibleHeightBar` https://github.com/bryankeller/BLKFlexibleHeightBar - a library I created several years ago for creating expanding and collapsing headers. It also takes the approach of decoupling the header from the scrolling view, which provides a bunch of flexibility (defining custom expand / collapse behavior, for example). I don't actively maintain that project, but going through the `README` might provide some inspiration for how to architect things in your app.
